version: "3.9"
services:
  haproxy:
    build: ./haproxy/.
    ports:
     - '8000:8080'
     - '8001:8081'
  web1:
    build: ./web/.
    hostname: web1
  web2:
    build: ./web/.
    hostname: web2
  web3:
    build: ./web/.
    hostname: web3
  web4:
    build: ./web/.
    hostname: web4
